// <auto-generated />
using System;
using IcantHumor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IcantHumor.Migrations
{
    [DbContext(typeof(IHDbContext))]
    [Migration("20231120151750_AddedFavouritesInUser")]
    partial class AddedFavouritesInUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryViewModelMediaViewModel", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "PostsId");

                    b.HasIndex("PostsId");

                    b.ToTable("CategoryViewModelMediaViewModel");
                });

            modelBuilder.Entity("IcantHumor.Models.CategoryViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IcantHumor.Models.FavouriteViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPost")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdReactedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserViewModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdPost");

                    b.HasIndex("UserViewModelId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("IcantHumor.Models.FullUserInfoViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ConfirmEmail")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FullInfoUsers");
                });

            modelBuilder.Entity("IcantHumor.Models.MediaViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdOfCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfFile")
                        .HasColumnType("int");

                    b.Property<string>("UrlToFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92330c7f-9141-475b-b99b-ab0d54d70b22"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 837, DateTimeKind.Local).AddTicks(9564),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 1",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("19263425-49b9-4787-9754-7d9c4d52d4bf"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 837, DateTimeKind.Local).AddTicks(9726),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 2",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("cfaa7a1d-dba3-4191-b147-fbf23ad4e901"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 837, DateTimeKind.Local).AddTicks(9776),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 3",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("44cc1920-16f2-457f-919b-994c64fe8bd7"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 837, DateTimeKind.Local).AddTicks(9823),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 4",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("c5ce4831-dcd6-45ac-93cc-f347b1abc25c"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 837, DateTimeKind.Local).AddTicks(9869),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 5",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("0a3804ea-cb33-4c5a-8a0a-1b30cb2b33e8"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 837, DateTimeKind.Local).AddTicks(9993),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 6",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("fa510361-d46b-46ff-a96a-341a2ddcac80"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(38),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 7",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("4212d386-64b0-49ba-b82a-d5afbda7b931"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(110),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 8",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("5cd01024-9ddc-4d0a-b058-45db990c34e8"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(157),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 9",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("4d0755af-c019-4409-9219-a590f415e634"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(212),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 10",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("db432c1d-086d-4009-85af-377b1221d005"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(260),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 11",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("3223c7f0-1250-4195-88a3-bd41d96028aa"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(305),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 12",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("df370f79-4efa-4548-ad1a-2013fd2cbbd2"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(349),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 13",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("d410c337-dfe5-438a-a1b6-2f74f2f2ed45"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(395),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 14",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("6d498141-2ee3-43f7-9e92-4a5adff7c621"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(440),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 15",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("91af7f30-3d22-4a78-b5c6-3bf9dcb2f889"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(494),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 16",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("8e90c18c-9b7c-48d3-9ead-026b8cf91c01"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(541),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 17",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("dada5fce-6b68-44b5-a49a-964d8365f405"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(590),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 18",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("284c620b-64e0-4bf3-bd73-8903e3418220"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(635),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 19",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("9d8c879a-1a2d-433c-9fed-e3ece139a88d"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(680),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 20",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("4b19f793-d515-44a5-9a9d-0009526647d8"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(726),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 21",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("a2bef41c-9ba6-4687-8758-fbdef8c1e4ec"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(771),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 22",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("1503ecfb-00a0-47c9-b963-70d5534c550f"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(852),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 23",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("d87c391d-210d-4b43-9001-31618b1ecd44"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(904),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 24",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("83ee3afb-d2ef-426a-accc-273bfa36b124"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(950),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 25",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("a613e5c4-d287-428f-ac5f-539fa64923d2"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(996),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 26",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("a77d4347-70ca-4bbb-85f6-4b0840937d53"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1041),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 27",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("554cb396-bf9a-4f5e-8de5-7d4c15f9bd98"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1085),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 28",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("3452e611-c6bb-4f65-a994-2adb34360ccd"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1130),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 29",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("2c3e80ef-c56f-4b0f-b064-4bf27c5a0e6e"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1175),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 30",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("e030f940-6405-4b99-86fa-71f83a26afc4"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1220),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 31",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("1a4c0087-186b-480d-9da5-01af81b62656"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1269),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 32",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("9f0bb2d9-b703-4058-b15c-dca91fe651a0"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1314),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 33",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("09dd27b9-ff6a-4ff9-9d6d-00eb87385af5"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1363),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 34",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("56d56a3a-a3f3-46ca-91a4-01d78e7ce604"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1407),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 35",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("ac2a9def-cefb-4a76-a85b-55c88ab438c0"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1450),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 36",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("1ed11aea-227f-45c1-89bc-4af8dbaf18f9"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1495),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 37",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("c943b5bb-4e68-43f0-9b6f-1b44607fd8ef"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1539),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 38",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("c1dd14e4-9eb2-44ca-8b67-19ea7acc7c95"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1585),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 39",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        },
                        new
                        {
                            Id = new Guid("da424347-9f05-4a7e-91b8-7090582bbb72"),
                            DateUpload = new DateTime(2023, 11, 20, 17, 17, 48, 838, DateTimeKind.Local).AddTicks(1634),
                            IdOfCreator = new Guid("01001b92-a37e-48f5-4ccf-08dbe68eb722"),
                            Title = "funny cat 40",
                            TypeOfFile = 0,
                            UrlToFile = "PostResources\\bebis.jpg"
                        });
                });

            modelBuilder.Entity("IcantHumor.Models.ReactedUserViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChosenReact")
                        .HasColumnType("int");

                    b.Property<Guid>("IdReactedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MediaViewModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MediaViewModelId");

                    b.ToTable("ReactedUsers");
                });

            modelBuilder.Entity("IcantHumor.Models.UserViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FullUserInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FullUserInfoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CategoryViewModelMediaViewModel", b =>
                {
                    b.HasOne("IcantHumor.Models.CategoryViewModel", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IcantHumor.Models.MediaViewModel", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IcantHumor.Models.FavouriteViewModel", b =>
                {
                    b.HasOne("IcantHumor.Models.MediaViewModel", "FavMedia")
                        .WithMany()
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IcantHumor.Models.UserViewModel", null)
                        .WithMany("Favourites")
                        .HasForeignKey("UserViewModelId");

                    b.Navigation("FavMedia");
                });

            modelBuilder.Entity("IcantHumor.Models.ReactedUserViewModel", b =>
                {
                    b.HasOne("IcantHumor.Models.MediaViewModel", null)
                        .WithMany("WhoReacted")
                        .HasForeignKey("MediaViewModelId");
                });

            modelBuilder.Entity("IcantHumor.Models.UserViewModel", b =>
                {
                    b.HasOne("IcantHumor.Models.FullUserInfoViewModel", "FullUserInfo")
                        .WithMany()
                        .HasForeignKey("FullUserInfoId");

                    b.Navigation("FullUserInfo");
                });

            modelBuilder.Entity("IcantHumor.Models.MediaViewModel", b =>
                {
                    b.Navigation("WhoReacted");
                });

            modelBuilder.Entity("IcantHumor.Models.UserViewModel", b =>
                {
                    b.Navigation("Favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
